apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.kafka.name }}-kafka-certificate-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm-store
  target:
    name: {{ .Values.kafka.name }}-kafka-certificate-secrets
    creationPolicy: Owner
  data:
    - secretKey: listener-certificate
      remoteRef:
        key: /certificates/kafka/certificate
    - secretKey: listener-key
      remoteRef:
        key: /certificates/kafka/key