kafka:
  name: clovers
  version: 3.6.0
  replicas: 3
  resources: {}
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    - name: tls
      port: 9094
      type: ingress
      tls: true
      authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          host: kafka-bootstrap.placeholder.clovers.ai
          annotations:
            external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.placeholder.clovers.ai.
            external-dns.alpha.kubernetes.io/ttl: "600"
        brokers:
          - broker: 0
            host: kafka-b0.placeholder.clovers.ai
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-b0.placeholder.clovers.ai.
              external-dns.alpha.kubernetes.io/ttl: "600"
          - broker: 1
            host: kafka-b1.placeholder.clovers.ai
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-b1.placeholder.clovers.ai.
              external-dns.alpha.kubernetes.io/ttl: "600"
          - broker: 2
            host: kafka-b2.placeholder.clovers.ai
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-b2.placeholder.clovers.ai.
              external-dns.alpha.kubernetes.io/ttl: "600"
        class: ingress-kafka
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: true
  jvmOptions:
    xms: 3092m
    xmx: 3092m
    metaspaceSize: 96m
    maxGCPauseMillis: 20
    initiatingHeapOccupancyPercent: 35
    g1HeapRegionSize: 16M
    minMetaspaceFreeRatio: 50
    maxMetaspaceFreeRatio: 80
    useG1GC: true
zookeeper:
  replicas: 3
  resources: {}
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: true
